env:
  global:
    secure: APJlMhvfTnqmYtQA9xev4HFlco1ucw7xikUaL4Bwx9gbsDGrzSWgJYDmMYu2mBgc6s+rSD8OFm51lVDtfXVdfmMs4dsuOAWxcXGPnr3SCmDovmbpIqdQXV3c2k1nGSVdhsH2yvA0rhWzGVTbWQxzuyHlBteRhFKOmJreXilpzL4=

language: node_js

node_js:
  - 0.10

script: "harp compile _harp _website"
after_success:
- ls
- ls utility
- source ./utility/initiate-publish.sh
